### ISSUE TITLE
one point in ethics principles needs clarification

### ISSUE THREAD

**Issue by Parikshit-Hooda** [Data4Democracy/ethics-resources#34]
I am part of an ecosystem understand context and provenance.
The above point under the title 'Ethics Principles' doesn't make sense and needs clarification. I think some words are missing. I would be happy to submit a PR to fix it in connect with hacktoberfest(2018)

**Comment by joeblankenship1** [comment]
That would be great! Let me know if you would like to discuss the statement or expand on it.

**Comment by Parikshit-Hooda** [comment]
Yes, I would very much love to discuss. Sorry for the late reply. Lets discuss the point here and then I will open a PR by correcting it. What I understood from the statement in question is I am a part of an ecosystem but I am not clear on the second part of the statement.

**Comment by joeblankenship1** [comment]
After re-reading this, this document needs reformatting writ-large. However, focusing on the statement above:

* "ecosystem" is a bit problematic, but is mentioned in the context of social benefit.
  * "Social Benefit: I set people before data and intend to be responsible for maximizing social benefit and minimizing harm. I will consider the impact of my work on communities of people, other living beings, ecosystems and the world-at-large." from the Readme.

So I think we could say that this statement is trying to state that:

* we as people who produce data and as people who use/analyze/mobilize data are responsible for understanding the places we're studying and how "what" we do affects these places in the long-term.

Does that make a bit more sense?

**Comment by Parikshit-Hooda** [comment]
I think we could rewrite the principle to  - 'I am part of an ecosystem and it is my duty to help it flourish'. Suggestions, comments?

**Comment by joeblankenship1** [comment]
"I am part of an ecosystem and it is my ethical obligation to produce considerate analysis conducive to standards of minimal impact and risk to communities, people, and the world." ???

**Comment by Parikshit-Hooda** [comment]
sounds good. Shall i open a pr?

**Comment by joeblankenship1** [comment]
Absolutely. :)

**Comment by Parikshit-Hooda** [comment]
pr opened. pr no. #39

**Comment by joeblankenship1** [comment]
PR was merged. I made a note about possible additions to principles and/or edits to this change.
